export type StoreId = "PMS" | "TP6";
export type DomainId = "PRODUCTION" | "WASTE" | "DAILY_SO";

export type ProductionWasteSkuId =
  | "GREEN_TEA_BASE"
  | "BLACK_TEA_BASE"
  | "OOLONG_TEA_BASE"
  | "OOLONG_TEA_LOCAL_BASE"
  | "ALISAN_TEA_BASE"
  | "MILK_TEA_BASE"
  | "MILK_TEA_LOCAL_BASE"
  | "EARL_GREY_MILK_TEA_BASE"
  | "EARL_GREY_TEA_BASE"
  | "WINTER_MELON_BASE"
  | "HONEY_BASE"
  | "MILK_COFFEE_BASE"
  | "BLACK_COFFEE_BASE"
  | "GREEN_TEA_LOCAL_BASE"
  | "BLACK_TEA_LOCAL_BASE"
  | "EARL_GREY_MILK_TEA_LOCAL_BASE"
  | "EARL_GREY_TEA_LOCAL_BASE"
  | "MILK_COFFEE_VARIETY_BASE"
  | "HERBAL_JELLY_BASE"
  | "AI_YU_BASE"
  | "PUDDING_BASE"
  | "PEARL_BASE"
  | "MILK_FOAM_BASE"
  | "PISTACHIO_MILK_FOAM_BASE"
  | "BANANA_FOAM_BASE"
  | "CHEESE_FOAM_BASE"
  | "CHEESE_CAKE_PUDDING"
  | "COFFEE_MILK_FOAM_BASE"
  | "MINI_PEARL_BASE"
  | "PEACH_YOGHURT_BASE"
  | "LYCHYEE_BASE";

export type DailySoSkuId =
  | "Y16_G1_MEDIUM_CUP"
  | "Y22_G1_LARGE_CUP"
  | "Y12_G1_SMALL_CUP"
  | "PAPER_CUP_16OZ"
  | "RAISED_COVER"
  | "PAPER_CUP_LID"
  | "MILLAC_GOLD_1LT"
  | "FRESH_MILK_DIAMOND_946ML"
  | "Y16_LOCAL_MEDIUM_CUP"
  | "HARRY_POTTER_CUP";

export type CanonicalSkuId = ProductionWasteSkuId | DailySoSkuId;
